---
- hosts: all
  become: true
  tasks:

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
    
  - name: Installing Docker
    apt:
      name: docker.io
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Installing Docker using Snap
    snap:
      name: docker
      state: present
      classic: yes
    when: ansible_distribution == "Ubuntu"

  - name: Start Docker service
    systemd:
      name: docker
      state: restarted
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Adding user "qcchavez" to Docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Creating a directory for Docker
    file:
      name: "/home/{{ ansible_user }}/docker-project"
      state: directory
      mode: '0755'
    when: ansible_distribution == "Ubuntu"

  - name: Copying Dockerfile to remote server
    copy:
      src: /home/qcchavez/CPE212_Chavez_HOA11.1/Dockerfile
      dest: "/home/{{ ansible_user }}/docker-project/Dockerfile"
      mode: '0644'
    when: ansible_distribution == "Ubuntu"

  - name: Copy index.html to remote server
    copy:
      src: /home/qcchavez/CPE212_Chavez_HOA11.1/index.html
      dest: "/home/{{ ansible_user }}/docker-project/index.html"
      mode: '0644'
    when: ansible_distribution == "Ubuntu"

  - name: Building Docker Image using Dockerfile
    docker_image:
      name: apache-mysql
      source: build
      build:
        path: "/home/{{ ansible_user }}/docker-project"
    when: ansible_distribution == "Ubuntu"

  - name: Running Docker Container
    docker_container:
      name: apache-mysql-container
      image: apache-mysql:latest
      state: started
      restart_policy: always
      ports:
        - "8080:80"
        - "3307:3306"
    when: ansible_distribution == "Ubuntu"
