---
- hosts: all
  become: true
  tasks:

  - name: Update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Install Docker
    apt:
      name: docker.io
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Start Docker service
    systemd:
      name: docker
      state: restarted
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Add user "qcchavez" to Docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Create directory for Docker project
    file:
      name: "/home/{{ ansible_user }}/docker-project"
      state: directory
      mode: '0755'
    when: ansible_distribution == "Ubuntu"

  - name: Copy Dockerfile to remote server
    copy:
      src: /home/qcchavez/CPE212_Chavez_HOA11.1/Dockerfile
      dest: "/home/{{ ansible_user }}/docker-project/Dockerfile"
      mode: '0644'
    when: ansible_distribution == "Ubuntu"

  - name: Copy index.html to remote server
    copy:
      src: /home/qcchavez/CPE212_Chavez_HOA11.1/index.html
      dest: "/home/{{ ansible_user }}/docker-project/index.html"
      mode: '0644'
    when: ansible_distribution == "Ubuntu"

  - name: Allow port 8080 for web access in UFW
    ufw:
      rule: allow
      port: '8080'
      proto: tcp
    when: ansible_distribution == "Ubuntu"

  - name: Build Docker Image using Dockerfile
    docker_image:
      name: apache-mysql
      source: build
      build:
        path: /home/{{ ansible_user }}/docker-project
        dockerfile: /home/{{ ansible_user }}/docker-project/Dockerfile
      force: yes  # Ensure the image is rebuilt even if it already exists
    when: ansible_distribution == "Ubuntu"

  - name: Run Docker Container
    docker_container:
      name: apache-mysql-container
      image: apache-mysql:latest
      state: started
      restart_policy: always
      ports:
        - "8080:80"
        - "3306:3306"
    when: ansible_distribution == "Ubuntu"

